latest update
git-svn-id: https://stage.maemo.org/svn/maemo/trunk@15 50eb543b-83fa-0310-9bb7-f7cbbee4ab39

diff --git a/hildon-fm/configure b/hildon-fm/configure
--- a/hildon-fm/configure
+++ b/hildon-fm/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL PKG_CONFIG OUTO_CFLAGS OUTO_LIBS GTK_CFLAGS GTK_LIBS GTK_VERSION GCONF_CFLAGS GCONF_LIBS OSSO_THUMBNAIL_CFLAGS OSSO_THUMBNAIL_LIBS GWCONNECT_CFLAGS GWCONNECT_LIBS DBUSGLIB_CFLAGS DBUSGLIB_LIBS LIBOSSO_CFLAGS LIBOSSO_LIBS ALL_LINGUAS USE_NLS MSGFMT GMSGFMT XGETTEXT CATALOGS CATOBJEXT DATADIRNAME GMOFILES INSTOBJEXT INTLLIBS PO_IN_DATADIR_TRUE PO_IN_DATADIR_FALSE POFILES POSUB MKINSTALLDIRS GTKDOC ENABLE_GTK_DOC_TRUE ENABLE_GTK_DOC_FALSE docdir localedir outomoduledir HTML_DIR LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL PKG_CONFIG OUTO_CFLAGS OUTO_LIBS GTK_CFLAGS GTK_LIBS GTK_VERSION GCONF_CFLAGS GCONF_LIBS OSSO_THUMBNAIL_CFLAGS OSSO_THUMBNAIL_LIBS GWCONNECT_CFLAGS GWCONNECT_LIBS DBUSGLIB_CFLAGS DBUSGLIB_LIBS LIBOSSO_CFLAGS LIBOSSO_LIBS BTTOOLS_CFLAGS BTTOOLS_LIBS MCE_CFLAGS MCE_LIBS ALL_LINGUAS USE_NLS MSGFMT GMSGFMT XGETTEXT CATALOGS CATOBJEXT DATADIRNAME GMOFILES INSTOBJEXT INTLLIBS PO_IN_DATADIR_TRUE PO_IN_DATADIR_FALSE POFILES POSUB MKINSTALLDIRS GTKDOC ENABLE_GTK_DOC_TRUE ENABLE_GTK_DOC_FALSE docdir localedir outomoduledir HTML_DIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1032,7 +1032,7 @@ Optional Features:
   --enable-fast-install[=PKGS]
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
-  --enable-logging=ARG    none, syslog, stdout, stderr (default=syslog)
+  --enable-logging=ARG    none, syslog, stdout, stderr (default=none)
   --enable-gtk-doc        use gtk-doc to build documenta
 tion default=yes
  --with-doc-dir=PATH path to installed docs
@@ -1774,7 +1774,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=hildon-fm
- VERSION=0.9.1
+ VERSION=0.9.24
 
 
 cat >>confdefs.h <<_ACEOF
@@ -2322,7 +2322,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link_default\"") >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
   # Find the output, starting from the most likely.  This scheme is
-# not robust to waste in `.', hence go to wildcards (a.*) only as a last
+# not robust to junk in `.', hence go to wildcards (a.*) only as a last
 # resort.
 
 # Be careful to initialize this variable, since it used to be cached.
@@ -19231,8 +19231,6 @@ _ACEOF
 fi
 
 
-LOGFLAGS="-DDEBUG"
-
 # Check whether --enable-logging or --disable-logging was given.
 if test "${enable_logging+set}" = set; then
   enableval="$enable_logging"
@@ -19351,7 +19349,7 @@ echo "$as_me: error: Library requirements (outo >= 0.1.1) not met; consider adju
 
 
 
-GTK_VERSION=2.4.0
+GTK_VERSION=2.6.0
 
 
   succeeded=no
@@ -19760,6 +19758,7 @@ echo "$as_me: error: Library requirements (gwconnect >= 0.58) not met; consider 
 
 
 
+# Updated required version. Old 0.23.1 is not compatible with 0.23.4
 
   succeeded=no
 
@@ -19814,23 +19813,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for dbus-glib-1 >= 0.23.1" >&5
-echo $ECHO_N "checking for dbus-glib-1 >= 0.23.1... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for dbus-glib-1 >= 0.23.4" >&5
+echo $ECHO_N "checking for dbus-glib-1 >= 0.23.4... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "dbus-glib-1 >= 0.23.1" ; then
+        if $PKG_CONFIG --exists "dbus-glib-1 >= 0.23.4" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking DBUSGLIB_CFLAGS" >&5
 echo $ECHO_N "checking DBUSGLIB_CFLAGS... $ECHO_C" >&6
-            DBUSGLIB_CFLAGS=`$PKG_CONFIG --cflags "dbus-glib-1 >= 0.23.1"`
+            DBUSGLIB_CFLAGS=`$PKG_CONFIG --cflags "dbus-glib-1 >= 0.23.4"`
             echo "$as_me:$LINENO: result: $DBUSGLIB_CFLAGS" >&5
 echo "${ECHO_T}$DBUSGLIB_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking DBUSGLIB_LIBS" >&5
 echo $ECHO_N "checking DBUSGLIB_LIBS... $ECHO_C" >&6
-            DBUSGLIB_LIBS=`$PKG_CONFIG --libs "dbus-glib-1 >= 0.23.1"`
+            DBUSGLIB_LIBS=`$PKG_CONFIG --libs "dbus-glib-1 >= 0.23.4"`
             echo "$as_me:$LINENO: result: $DBUSGLIB_LIBS" >&5
 echo "${ECHO_T}$DBUSGLIB_LIBS" >&6
         else
@@ -19838,7 +19837,7 @@ echo "${ECHO_T}$DBUSGLIB_LIBS" >&6
             DBUSGLIB_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            DBUSGLIB_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "dbus-glib-1 >= 0.23.1"`
+            DBUSGLIB_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "dbus-glib-1 >= 0.23.4"`
             echo $DBUSGLIB_PKG_ERRORS
         fi
 
@@ -19853,8 +19852,8 @@ echo "${ECHO_T}$DBUSGLIB_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (dbus-glib-1 >= 0.23.1) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (dbus-glib-1 >= 0.23.1) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (dbus-glib-1 >= 0.23.4) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (dbus-glib-1 >= 0.23.4) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
@@ -19962,7 +19961,207 @@ echo "$as_me: error: Library requirements (libosso >= 0.8.8) not met; consider a
 
 
 
-# We should check for MCE, but it doesn't have pkgconfig, bug #7999
+# We need only macros from bttools-dev package
+
+  succeeded=no
+
+  if test -z "$PKG_CONFIG"; then
+    # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_PKG_CONFIG" && ac_cv_path_PKG_CONFIG="no"
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+
+if test -n "$PKG_CONFIG"; then
+  echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+echo "${ECHO_T}$PKG_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  fi
+
+  if test "$PKG_CONFIG" = "no" ; then
+     echo "*** The pkg-config script could not be found. Make sure it is"
+     echo "*** in your path, or set the PKG_CONFIG environment variable"
+     echo "*** to the full path to pkg-config."
+     echo "*** Or see http://www.freedesktop.org/software/pkgconfig to get pkg-config."
+  else
+     PKG_CONFIG_MIN_VERSION=0.9.0
+     if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
+        echo "$as_me:$LINENO: checking for bttools >= 0.22" >&5
+echo $ECHO_N "checking for bttools >= 0.22... $ECHO_C" >&6
+
+        if $PKG_CONFIG --exists "bttools >= 0.22" ; then
+            echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+            succeeded=yes
+
+            echo "$as_me:$LINENO: checking BTTOOLS_CFLAGS" >&5
+echo $ECHO_N "checking BTTOOLS_CFLAGS... $ECHO_C" >&6
+            BTTOOLS_CFLAGS=`$PKG_CONFIG --cflags "bttools >= 0.22"`
+            echo "$as_me:$LINENO: result: $BTTOOLS_CFLAGS" >&5
+echo "${ECHO_T}$BTTOOLS_CFLAGS" >&6
+
+            echo "$as_me:$LINENO: checking BTTOOLS_LIBS" >&5
+echo $ECHO_N "checking BTTOOLS_LIBS... $ECHO_C" >&6
+            BTTOOLS_LIBS=`$PKG_CONFIG --libs "bttools >= 0.22"`
+            echo "$as_me:$LINENO: result: $BTTOOLS_LIBS" >&5
+echo "${ECHO_T}$BTTOOLS_LIBS" >&6
+        else
+            BTTOOLS_CFLAGS=""
+            BTTOOLS_LIBS=""
+            ## If we have a custom action on failure, don't print errors, but
+            ## do set a variable so people can do so.
+            BTTOOLS_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "bttools >= 0.22"`
+            echo $BTTOOLS_PKG_ERRORS
+        fi
+
+
+
+     else
+        echo "*** Your version of pkg-config is too old. You need version $PKG_CONFIG_MIN_VERSION or newer."
+        echo "*** See http://www.freedesktop.org/software/pkgconfig"
+     fi
+  fi
+
+  if test $succeeded = yes; then
+     :
+  else
+     { { echo "$as_me:$LINENO: error: Library requirements (bttools >= 0.22) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (bttools >= 0.22) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
+
+# Now also mce has a pkgconfig file.
+
+  succeeded=no
+
+  if test -z "$PKG_CONFIG"; then
+    # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_PKG_CONFIG" && ac_cv_path_PKG_CONFIG="no"
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+
+if test -n "$PKG_CONFIG"; then
+  echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+echo "${ECHO_T}$PKG_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  fi
+
+  if test "$PKG_CONFIG" = "no" ; then
+     echo "*** The pkg-config script could not be found. Make sure it is"
+     echo "*** in your path, or set the PKG_CONFIG environment variable"
+     echo "*** to the full path to pkg-config."
+     echo "*** Or see http://www.freedesktop.org/software/pkgconfig to get pkg-config."
+  else
+     PKG_CONFIG_MIN_VERSION=0.9.0
+     if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
+        echo "$as_me:$LINENO: checking for mce >= 0.8.5" >&5
+echo $ECHO_N "checking for mce >= 0.8.5... $ECHO_C" >&6
+
+        if $PKG_CONFIG --exists "mce >= 0.8.5" ; then
+            echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+            succeeded=yes
+
+            echo "$as_me:$LINENO: checking MCE_CFLAGS" >&5
+echo $ECHO_N "checking MCE_CFLAGS... $ECHO_C" >&6
+            MCE_CFLAGS=`$PKG_CONFIG --cflags "mce >= 0.8.5"`
+            echo "$as_me:$LINENO: result: $MCE_CFLAGS" >&5
+echo "${ECHO_T}$MCE_CFLAGS" >&6
+
+            echo "$as_me:$LINENO: checking MCE_LIBS" >&5
+echo $ECHO_N "checking MCE_LIBS... $ECHO_C" >&6
+            MCE_LIBS=`$PKG_CONFIG --libs "mce >= 0.8.5"`
+            echo "$as_me:$LINENO: result: $MCE_LIBS" >&5
+echo "${ECHO_T}$MCE_LIBS" >&6
+        else
+            MCE_CFLAGS=""
+            MCE_LIBS=""
+            ## If we have a custom action on failure, don't print errors, but
+            ## do set a variable so people can do so.
+            MCE_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "mce >= 0.8.5"`
+            echo $MCE_PKG_ERRORS
+        fi
+
+
+
+     else
+        echo "*** Your version of pkg-config is too old. You need version $PKG_CONFIG_MIN_VERSION or newer."
+        echo "*** See http://www.freedesktop.org/software/pkgconfig"
+     fi
+  fi
+
+  if test $succeeded = yes; then
+     :
+  else
+     { { echo "$as_me:$LINENO: error: Library requirements (mce >= 0.8.5) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (mce >= 0.8.5) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
 
 ALL_LINGUAS="en_GB"
 
@@ -22381,6 +22580,10 @@ s,@DBUSGLIB_CFLAGS@,$DBUSGLIB_CFLAGS,;t t
 s,@DBUSGLIB_LIBS@,$DBUSGLIB_LIBS,;t t
 s,@LIBOSSO_CFLAGS@,$LIBOSSO_CFLAGS,;t t
 s,@LIBOSSO_LIBS@,$LIBOSSO_LIBS,;t t
+s,@BTTOOLS_CFLAGS@,$BTTOOLS_CFLAGS,;t t
+s,@BTTOOLS_LIBS@,$BTTOOLS_LIBS,;t t
+s,@MCE_CFLAGS@,$MCE_CFLAGS,;t t
+s,@MCE_LIBS@,$MCE_LIBS,;t t
 s,@ALL_LINGUAS@,$ALL_LINGUAS,;t t
 s,@USE_NLS@,$USE_NLS,;t t
 s,@MSGFMT@,$MSGFMT,;t t
