2005-10-13  Karoliina Salminen  <karoliina.t.salminen@nokia.com>         * Increased version number to 1.60.0, preparing for next integration round         * Patched bug N#20305: Desktop doesn't close applications on exit         * hildon-navigator/windowmanager.c (kill_all): Allow also the         topmost application to be killed, when killable_only is set to         FALSE (indicates that Task Navigator and apps are about to         restart/shutdown anyway)
git-svn-id: https://stage.maemo.org/svn/maemo/projects/haf/trunk@1192 50eb543b-83fa-0310-9bb7-f7cbbee4ab39

diff --git a/maemo-af-desktop/configure b/maemo-af-desktop/configure
--- a/maemo-af-desktop/configure
+++ b/maemo-af-desktop/configure
@@ -1777,7 +1777,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=maemo-af-desktop
- VERSION=1.59.0
+ VERSION=1.60.0
 
 
 cat >>confdefs.h <<_ACEOF
@@ -22309,23 +22309,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for libosso >= 0.9.18 " >&5
-echo $ECHO_N "checking for libosso >= 0.9.18 ... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for libosso >= 0.9.19 " >&5
+echo $ECHO_N "checking for libosso >= 0.9.19 ... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "libosso >= 0.9.18 " ; then
+        if $PKG_CONFIG --exists "libosso >= 0.9.19 " ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking OSSO_CFLAGS" >&5
 echo $ECHO_N "checking OSSO_CFLAGS... $ECHO_C" >&6
-            OSSO_CFLAGS=`$PKG_CONFIG --cflags "libosso >= 0.9.18 "`
+            OSSO_CFLAGS=`$PKG_CONFIG --cflags "libosso >= 0.9.19 "`
             echo "$as_me:$LINENO: result: $OSSO_CFLAGS" >&5
 echo "${ECHO_T}$OSSO_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking OSSO_LIBS" >&5
 echo $ECHO_N "checking OSSO_LIBS... $ECHO_C" >&6
-            OSSO_LIBS=`$PKG_CONFIG --libs "libosso >= 0.9.18 "`
+            OSSO_LIBS=`$PKG_CONFIG --libs "libosso >= 0.9.19 "`
             echo "$as_me:$LINENO: result: $OSSO_LIBS" >&5
 echo "${ECHO_T}$OSSO_LIBS" >&6
         else
@@ -22333,7 +22333,7 @@ echo "${ECHO_T}$OSSO_LIBS" >&6
             OSSO_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            OSSO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libosso >= 0.9.18 "`
+            OSSO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libosso >= 0.9.19 "`
             echo $OSSO_PKG_ERRORS
         fi
 
@@ -22348,8 +22348,8 @@ echo "${ECHO_T}$OSSO_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (libosso >= 0.9.18 ) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (libosso >= 0.9.18 ) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (libosso >= 0.9.19 ) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (libosso >= 0.9.19 ) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
