2006-03-08  Johan Bilien <johan.bilien@nokia.com> 	* hildon-home/hildon-home-main.[ch]:       - global menu status flag added 	  - hildon_home_key_press_listener(): removed widget grabing add. Menu 	    closing added when open and menu key is pressed. 	  - hildon_home_key_release_listener(): removed widget grabing remove       - Closes N#22637 	* configure.ac: Don't check for hildon-lgpl which is deprecated 	* hildon-navigator/hn-wm.c: 	  - hn_wm_compute_watched_window_hibernation_key(): Replaced 	    conditional gdk_error_trap_pop with unconditional one 	    (Closes N#23940)
git-svn-id: https://stage.maemo.org/svn/maemo/projects/haf/trunk@2657 50eb543b-83fa-0310-9bb7-f7cbbee4ab39

diff --git a/maemo-af-desktop/configure b/maemo-af-desktop/configure
--- a/maemo-af-desktop/configure
+++ b/maemo-af-desktop/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP RANLIB ac_ct_RANLIB EGREP LN_S ECHO AR ac_ct_AR CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS ALL_LINGUAS USE_NLS MSGFMT GMSGFMT XGETTEXT CATALOGS CATOBJEXT DATADIRNAME GMOFILES INSTOBJEXT INTLLIBS PO_IN_DATADIR_TRUE PO_IN_DATADIR_FALSE POFILES POSUB MKINSTALLDIRS PKG_CONFIG HILDON_FM_CFLAGS HILDON_FM_LIBS LIBXML_CFLAGS LIBXML_LIBS OSSO_CFLAGS OSSO_LIBS MB_CFLAGS MB_LIBS HILDON_CFLAGS HILDON_LIBS HILDONBASELIB_CFLAGS HILDONBASELIB_LIBS GCONF_CFLAGS GCONF_LIBS GNOME_VFS_CFLAGS GNOME_VFS_LIBS GDK_CFLAGS GDK_LIBS OSSOSETTINGS_CFLAGS OSSOSETTINGS_LIBS localedir COMMON_ERROR_CFLAGS COMMON_ERROR_LIBS XLIBS_CFLAGS XLIBS_LIBS XLIBS_ERROR_LIBS OSSO_HELP_CFLAGS OSSO_HELP_LIBS OSSO_HELP_ERROR_LIBS hildonhomedesktopentrydir hildondesktopentrydir hildoncpdesktopentrydir hildonnavigatorlibdir hildonhomelibdir hildonstatusbarlibdir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP RANLIB ac_ct_RANLIB EGREP LN_S ECHO AR ac_ct_AR CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS ALL_LINGUAS USE_NLS MSGFMT GMSGFMT XGETTEXT CATALOGS CATOBJEXT DATADIRNAME GMOFILES INSTOBJEXT INTLLIBS PO_IN_DATADIR_TRUE PO_IN_DATADIR_FALSE POFILES POSUB MKINSTALLDIRS PKG_CONFIG HILDON_FM_CFLAGS HILDON_FM_LIBS LIBXML_CFLAGS LIBXML_LIBS OSSO_CFLAGS OSSO_LIBS MB_CFLAGS MB_LIBS HILDONBASELIB_CFLAGS HILDONBASELIB_LIBS HILDON_CFLAGS HILDON_LIBS GCONF_CFLAGS GCONF_LIBS GNOME_VFS_CFLAGS GNOME_VFS_LIBS GDK_CFLAGS GDK_LIBS OSSOSETTINGS_CFLAGS OSSOSETTINGS_LIBS localedir COMMON_ERROR_CFLAGS COMMON_ERROR_LIBS XLIBS_CFLAGS XLIBS_LIBS XLIBS_ERROR_LIBS OSSO_HELP_CFLAGS OSSO_HELP_LIBS OSSO_HELP_ERROR_LIBS hildonhomedesktopentrydir hildondesktopentrydir hildoncpdesktopentrydir hildonnavigatorlibdir hildonhomelibdir hildonstatusbarlibdir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -22714,107 +22714,6 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for hildon-lgpl >= 0.9.1" >&5
-echo $ECHO_N "checking for hildon-lgpl >= 0.9.1... $ECHO_C" >&6
-
-        if $PKG_CONFIG --exists "hildon-lgpl >= 0.9.1" ; then
-            echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-            succeeded=yes
-
-            echo "$as_me:$LINENO: checking HILDON_CFLAGS" >&5
-echo $ECHO_N "checking HILDON_CFLAGS... $ECHO_C" >&6
-            HILDON_CFLAGS=`$PKG_CONFIG --cflags "hildon-lgpl >= 0.9.1"`
-            echo "$as_me:$LINENO: result: $HILDON_CFLAGS" >&5
-echo "${ECHO_T}$HILDON_CFLAGS" >&6
-
-            echo "$as_me:$LINENO: checking HILDON_LIBS" >&5
-echo $ECHO_N "checking HILDON_LIBS... $ECHO_C" >&6
-            HILDON_LIBS=`$PKG_CONFIG --libs "hildon-lgpl >= 0.9.1"`
-            echo "$as_me:$LINENO: result: $HILDON_LIBS" >&5
-echo "${ECHO_T}$HILDON_LIBS" >&6
-        else
-            HILDON_CFLAGS=""
-            HILDON_LIBS=""
-            ## If we have a custom action on failure, don't print errors, but
-            ## do set a variable so people can do so.
-            HILDON_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "hildon-lgpl >= 0.9.1"`
-            echo $HILDON_PKG_ERRORS
-        fi
-
-
-
-     else
-        echo "*** Your version of pkg-config is too old. You need version $PKG_CONFIG_MIN_VERSION or newer."
-        echo "*** See http://www.freedesktop.org/software/pkgconfig"
-     fi
-  fi
-
-  if test $succeeded = yes; then
-     :
-  else
-     { { echo "$as_me:$LINENO: error: Library requirements (hildon-lgpl >= 0.9.1) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (hildon-lgpl >= 0.9.1) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-
-
-  succeeded=no
-
-  if test -z "$PKG_CONFIG"; then
-    # Extract the first word of "pkg-config", so it can be a program name with args.
-set dummy pkg-config; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $PKG_CONFIG in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-  test -z "$ac_cv_path_PKG_CONFIG" && ac_cv_path_PKG_CONFIG="no"
-  ;;
-esac
-fi
-PKG_CONFIG=$ac_cv_path_PKG_CONFIG
-
-if test -n "$PKG_CONFIG"; then
-  echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
-echo "${ECHO_T}$PKG_CONFIG" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-  fi
-
-  if test "$PKG_CONFIG" = "no" ; then
-     echo "*** The pkg-config script could not be found. Make sure it is"
-     echo "*** in your path, or set the PKG_CONFIG environment variable"
-     echo "*** to the full path to pkg-config."
-     echo "*** Or see http://www.freedesktop.org/software/pkgconfig to get pkg-config."
-  else
-     PKG_CONFIG_MIN_VERSION=0.9.0
-     if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
         echo "$as_me:$LINENO: checking for hildon-base-lib >= 0.7.4" >&5
 echo $ECHO_N "checking for hildon-base-lib >= 0.7.4... $ECHO_C" >&6
 
@@ -22916,23 +22815,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for hildon-libs >= 0.7.1" >&5
-echo $ECHO_N "checking for hildon-libs >= 0.7.1... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for hildon-libs >= 0.12.0" >&5
+echo $ECHO_N "checking for hildon-libs >= 0.12.0... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "hildon-libs >= 0.7.1" ; then
+        if $PKG_CONFIG --exists "hildon-libs >= 0.12.0" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking HILDON_CFLAGS" >&5
 echo $ECHO_N "checking HILDON_CFLAGS... $ECHO_C" >&6
-            HILDON_CFLAGS=`$PKG_CONFIG --cflags "hildon-libs >= 0.7.1"`
+            HILDON_CFLAGS=`$PKG_CONFIG --cflags "hildon-libs >= 0.12.0"`
             echo "$as_me:$LINENO: result: $HILDON_CFLAGS" >&5
 echo "${ECHO_T}$HILDON_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking HILDON_LIBS" >&5
 echo $ECHO_N "checking HILDON_LIBS... $ECHO_C" >&6
-            HILDON_LIBS=`$PKG_CONFIG --libs "hildon-libs >= 0.7.1"`
+            HILDON_LIBS=`$PKG_CONFIG --libs "hildon-libs >= 0.12.0"`
             echo "$as_me:$LINENO: result: $HILDON_LIBS" >&5
 echo "${ECHO_T}$HILDON_LIBS" >&6
         else
@@ -22940,7 +22839,7 @@ echo "${ECHO_T}$HILDON_LIBS" >&6
             HILDON_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            HILDON_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "hildon-libs >= 0.7.1"`
+            HILDON_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "hildon-libs >= 0.12.0"`
             echo $HILDON_PKG_ERRORS
         fi
 
@@ -22955,8 +22854,8 @@ echo "${ECHO_T}$HILDON_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (hildon-libs >= 0.7.1) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (hildon-libs >= 0.7.1) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (hildon-libs >= 0.12.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (hildon-libs >= 0.12.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
@@ -25996,10 +25895,10 @@ s,@OSSO_CFLAGS@,$OSSO_CFLAGS,;t t
 s,@OSSO_LIBS@,$OSSO_LIBS,;t t
 s,@MB_CFLAGS@,$MB_CFLAGS,;t t
 s,@MB_LIBS@,$MB_LIBS,;t t
-s,@HILDON_CFLAGS@,$HILDON_CFLAGS,;t t
-s,@HILDON_LIBS@,$HILDON_LIBS,;t t
 s,@HILDONBASELIB_CFLAGS@,$HILDONBASELIB_CFLAGS,;t t
 s,@HILDONBASELIB_LIBS@,$HILDONBASELIB_LIBS,;t t
+s,@HILDON_CFLAGS@,$HILDON_CFLAGS,;t t
+s,@HILDON_LIBS@,$HILDON_LIBS,;t t
 s,@GCONF_CFLAGS@,$GCONF_CFLAGS,;t t
 s,@GCONF_LIBS@,$GCONF_LIBS,;t t
 s,@GNOME_VFS_CFLAGS@,$GNOME_VFS_CFLAGS,;t t
